/**
 * HTTP error taxonomy.
 *
 * Every error that reaches a client passes through here, and the mapping is
 * deliberately conservative about what it says. Two rules:
 *
 *  1. Unknown errors become a bare 500 with a request id. Whatever a Postgres
 *     error message contains — a column name, a constraint body, part of a query
 *     — none of it goes to a client who may be a co-managed customer.
 *
 *  2. "Not found" and "not yours" are the same response. The database already
 *     refuses to distinguish them (helm.reveal_secret returns `not_found` for
 *     both); an API that renders a different message for each would hand that
 *     distinction straight back.
 */

/**
 * A note on identifier validation, since it appears in every route:
 *
 * Helm validates UUIDs with `z.guid()`, not `z.uuid()`. Zod 4's `uuid()`
 * enforces the RFC 4122 version nibble, which PostgreSQL's `uuid` type does
 * not — it stores any 128-bit value. An identifier imported from an RMM or PSA,
 * or generated by an older system, is frequently not RFC 4122 versioned, and
 * rejecting it at the API boundary would make real records permanently
 * unreachable while adding no safety: the shape check is what prevents
 * malformed input reaching the database, and the version nibble carries no
 * security meaning.
 */
export type ErrorCode =
  | 'unauthenticated'
  | 'forbidden'
  | 'not_found'
  | 'invalid_request'
  | 'conflict'
  | 'step_up_required'
  | 'reason_required'
  | 'rate_limited'
  | 'internal';

const STATUS: Record<ErrorCode, number> = {
  unauthenticated: 401,
  forbidden: 403,
  not_found: 404,
  invalid_request: 400,
  conflict: 409,
  // 403 with a distinguishable body: the client needs to know a re-auth prompt
  // would actually help, rather than showing "ask your manager".
  step_up_required: 403,
  reason_required: 403,
  rate_limited: 429,
  internal: 500,
};

export class ApiError extends Error {
  readonly code: ErrorCode;
  readonly status: number;
  /** Safe to serialise to the client. Never populated from a database error. */
  readonly details: Record<string, unknown> | undefined;

  constructor(code: ErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.status = STATUS[code];
    this.details = details;
  }

  static unauthenticated(message = 'authentication required'): ApiError {
    return new ApiError('unauthenticated', message);
  }

  static forbidden(message = 'not permitted', details?: Record<string, unknown>): ApiError {
    return new ApiError('forbidden', message, details);
  }

  /**
   * Use this for "you may not see it" as well as "it does not exist".
   * Distinguishing them is an enumeration oracle.
   */
  static notFound(message = 'not found'): ApiError {
    return new ApiError('not_found', message);
  }

  static invalid(message: string, details?: Record<string, unknown>): ApiError {
    return new ApiError('invalid_request', message, details);
  }

  static conflict(message: string, details?: Record<string, unknown>): ApiError {
    return new ApiError('conflict', message, details);
  }
}

export interface ErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
    requestId: string;
  };
}

export function toErrorBody(error: ApiError, requestId: string): ErrorBody {
  return {
    error: {
      code: error.code,
      message: error.message,
      ...(error.details ? { details: error.details } : {}),
      requestId,
    },
  };
}
