#!/usr/bin/env bash
# =============================================================================
# Generate every key and password Helm needs, once, with the right permissions.
#
# This exists because three of them have requirements that are easy to get
# subtly wrong and that fail in confusing ways:
#
#   * The master key file must be mode 0400 and owned by the container's uid
#     (10001). Helm refuses to start from a key file that is group- or
#     world-readable — including the 0444 that `docker secret` produces by
#     default — and a file owned by root that the container cannot read fails
#     with a permission error that reads like a bug.
#
#   * The key ring is versioned JSON, not a bare key. A bare key works, but it
#     is treated as version "v1" and rotating it later means editing the file
#     by hand. Starting versioned costs nothing.
#
#   * The blind index key must NOT be derivable from the master key. They are
#     generated independently here for that reason.
#
# Safe to inspect before running. It writes nothing outside deploy/ and .env,
# and it refuses to overwrite either.
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."

SECRETS_DIR="deploy/secrets"
KEY_FILE="${SECRETS_DIR}/master.key"
ENV_FILE=".env"

# The uid baked into the runtime image. Not arbitrary: the master key file must
# be readable by exactly this user and nobody else.
HELM_UID=10001
HELM_GID=10001

red()  { printf '\033[31m%s\033[0m\n' "$*"; }
note() { printf '  %s\n' "$*"; }

if ! command -v openssl >/dev/null 2>&1; then
  red "openssl is required to generate keys."
  exit 1
fi

# -----------------------------------------------------------------------------
# Refuse to clobber. Overwriting master.key makes every stored credential
# permanently unrecoverable, so this is a hard stop rather than a prompt.
# -----------------------------------------------------------------------------
if [ -e "$KEY_FILE" ]; then
  red "REFUSING: ${KEY_FILE} already exists."
  note "Overwriting the master key would make every credential in the database"
  note "permanently unrecoverable. To rotate it properly, add a new version to"
  note "the existing key ring and run: pnpm helm:rotate-kek"
  note "See docs/deployment/on-premises.md §8."
  exit 1
fi

if [ -e "$ENV_FILE" ]; then
  red "REFUSING: ${ENV_FILE} already exists."
  note "Delete or move it if you genuinely want a fresh set of credentials —"
  note "but note the database passwords in it are already in use by the running"
  note "Postgres volume, and changing them here alone will lock Helm out."
  exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
  red "This script must run as root (or under sudo)."
  note "It chowns the master key to uid ${HELM_UID}, the container's user."
  exit 1
fi

mkdir -p "$SECRETS_DIR"
chmod 0700 "$SECRETS_DIR"

echo "Generating secrets for Lake Effect Helm"
echo

# -----------------------------------------------------------------------------
# Master key ring
# -----------------------------------------------------------------------------
umask 077
printf '{\n  "current": "v1",\n  "keys": {\n    "v1": "%s"\n  }\n}\n' \
  "$(openssl rand -base64 32)" > "$KEY_FILE"

chown "${HELM_UID}:${HELM_GID}" "$KEY_FILE"
chmod 0400 "$KEY_FILE"

echo "master key      ${KEY_FILE} (mode 0400, uid ${HELM_UID})"
note "Back this up somewhere OFF this host, encrypted. Without it the database"
note "is a pile of ciphertext — there is no recovery path, by design."
echo

# -----------------------------------------------------------------------------
# Application secrets and database passwords
#
# Passwords avoid characters that need escaping inside a Postgres connection
# URL. -hex rather than -base64 for exactly that reason: a '/' or '+' in a
# password produces a connection string that parses wrong and an error that
# points nowhere near the cause.
# -----------------------------------------------------------------------------
pw() { openssl rand -hex 24; }

cat > "$ENV_FILE" <<ENVEOF
# Generated by deploy/init-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Contains every credential this deployment uses. Mode 0600, never committed,
# and worth backing up alongside the master key — losing the database passwords
# means rebuilding the roles by hand.

# --- Where Helm is reached -----------------------------------------------
# Must match the certificate and what people type in a browser. AUTH_URL is
# derived from it, and an Auth.js callback that disagrees with the address in
# the address bar fails in a way that is tedious to diagnose.
HELM_PUBLIC_HOST=helm.internal.example.com
HELM_PUBLIC_URL=https://helm.internal.example.com

# Caddy's internal CA by default: no public DNS, no ACME. Trust its root on the
# technicians' machines (setup guide §4), or point this at your own cert:
#   HELM_TLS_DIRECTIVE=tls /etc/helm/tls/helm.crt /etc/helm/tls/helm.key
HELM_TLS_DIRECTIVE=tls internal
HELM_HTTP_PORT=80
HELM_HTTPS_PORT=443

# --- Master key -----------------------------------------------------------
# local-keyfile: the key lives on this host, in deploy/secrets/master.key.
# vault-transit: the key never enters the Helm process. Set VAULT_ADDR and
# either VAULT_ROLE_ID/VAULT_SECRET_ID or VAULT_TOKEN, and point at an EXTERNAL
# Vault — one inside this stack would sit on the same host as the data.
HELM_KEK_PROVIDER=local-keyfile
HELM_KEK_ID=helm-master

VAULT_ADDR=
VAULT_NAMESPACE=
HELM_VAULT_TRANSIT_MOUNT=transit
HELM_VAULT_TRANSIT_KEY=helm-tenant-kek
VAULT_ROLE_ID=
VAULT_SECRET_ID=

# --- Application secrets --------------------------------------------------
AUTH_SECRET=$(openssl rand -base64 32)

# Derives per-tenant HMACs for password-reuse detection. Independent of the
# master key on purpose: if it were derivable from the KEK, anyone who obtained
# the KEK could also correlate reused credentials offline.
HELM_BLIND_INDEX_KEY_B64=$(openssl rand -base64 32)

# --- Database ---------------------------------------------------------------
# Five roles, five passwords. The separation is the product's security model:
# a bug in the request path cannot reach the auth token store, nothing in the
# request path can write a key, and nothing in the request path can enumerate
# tenants.
#
# These are consumed on FIRST START only, when the Postgres volume is
# initialised. Changing one here later does not change it in the database —
# see the setup guide for how to rotate one properly.
HELM_DB_PASSWORD_SUPERUSER=$(pw)
HELM_DB_PASSWORD_APP=$(pw)
HELM_DB_PASSWORD_AUTH=$(pw)
HELM_DB_PASSWORD_KEY_ADMIN=$(pw)
HELM_DB_PASSWORD_AUDITOR=$(pw)
HELM_DB_PASSWORD_WORKER=$(pw)

# --- Optional -------------------------------------------------------------
# Redis is NOT required. Worker mutual exclusion is a Postgres advisory lock,
# so correctness does not depend on it. Set this and run with
# \`--profile queue\` only if you need queue throughput.
REDIS_URL=

# debug | info | warn | error
HELM_LOG_LEVEL=info

# SSO. Leave blank to disable; see setup guide §5 for the Entra redirect URI.
AUTH_MICROSOFT_ENTRA_ID_ID=
AUTH_MICROSOFT_ENTRA_ID_SECRET=
AUTH_MICROSOFT_ENTRA_ID_ISSUER=
ENVEOF

chmod 0600 "$ENV_FILE"
echo "environment     ${ENV_FILE} (mode 0600)"
echo

echo "Next:"
note "1. Edit ${ENV_FILE} and set HELM_PUBLIC_HOST and HELM_PUBLIC_URL."
note "2. docker compose up -d"
note "3. Create the first tenant and administrator — setup guide §6."
echo
red "Back up ${KEY_FILE} and ${ENV_FILE} off this host before going further."
